config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  devise_for :users, controllers: {  registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lessons
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
  end

  resources :users, only: [:index, :edit, :update, :show]
  root 'home#index'
  get 'activity', to: 'home#activity'
  get 'privacy_policy', to: 'home#privacy_policy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :privacy_policy]


  def index
    @courses = Course.all.limit(3)
    @latest_courses = Course.published.approved.limit(3).order("created_at DESC")
    @enrollments = Enrollment.reviewed.order(rating: :desc).limit(3)
    @top_rated_courses = Course.published.approved.order(average_rating: :desc, created_at: :desc).limit(3)
    @popular_courses = Course.published.approved.order(enrollments_count: :desc, created_at: :desc).limit(3)
    @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
  end

  def activity
    @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
  end


  def privacy_policy
    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.erb
  <h3 class="text-center">Activities 
    <div class="badge badge-primary"><%= @activities.count %></div>
  </h3>


<% @activities.each do |activity| %>
  <ul class="list-group">
    <li class="list-group-item">
      <%= activity.created_at.strftime("%d-%m-%Y %H:%M") %>
      <%= activity.trackable_type %>
      <% if activity.trackable_type == "Lesson" %>
        <% if Lesson.where(id: activity.trackable_id).present? %>
          <%= link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable) %>
        <% else %>
          Lesson was deleted
        <% end %>
      <% elsif activity.trackable_type == "Comment" %>
        <% if Comment.where(id: activity.trackable_id).present? %>
          <%= link_to activity.trackable.content, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson) %>
        <% else %>
          Comment was deleted
        <% end %>
      <% else %>
        <%= link_to activity.trackable, activity.trackable %>
      <% end %>
      <%= activity.key %>
      by
      <%= link_to activity.owner.email, user_path(activity.owner) %>
      <%= time_ago_in_words(activity.created_at) %>
      <% if activity.parameters.any? %>
        <%= activity.parameters %>
      <% end %>
    </li>
  </ul>
<% end %>


<div class="mt-2">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/home/index.html.erb
<% content_for :title do %>
  CourseApp | Learn now!
<% end %>

<div class="jumbotron my-5">
  <h1 class="display-4 pb-4">What do you want to learn today?</h1>
  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eum nesciunt magni ipsum, illum consectetur aut quod itaque id enim suscipit soluta minima. Optio odio placeat ex, deleniti vitae voluptates maiores?</p>
  <% unless current_user %>
    <hr class="my-5">
    <div class="row ">
      <div class="col-md-6 d-flex justify-content-around">
        <div class="btn-group-vertical">
        <h3 class="text-shadow">Join to access all the courses</h3>
          <div class="btn-group">
            <%= link_to 'Register', new_user_registration_path, class: 'btn btn-light btn-lg' %>
            <%= link_to 'Login', new_user_session_path, class: 'btn btn-light btn-lg' %>
          </div>
          <%= link_to user_google_oauth2_omniauth_authorize_path, class: 'btn btn-danger btn-lg' do %>
            Continue with
            <div class="fab fa-google"></div>
          <% end %>
          <%= link_to user_github_omniauth_authorize_path, class: 'btn btn-dark btn-lg' do %>
            Continue with
            <div class="fab fa-github"></div>
          <% end %>
          <%= link_to user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-lg' do %>
            Continue with
            <div class="fab fa-facebook"></div>
          <% end %>
        </div>
      </div>
      <div class="col-md-6 mt-3 mt-md-0 d-flex justify-content-around">
        <div class="btn-group-vertical">
          <h3 class="text-shadow">Check our courses</h3>
          <%= link_to courses_path, class: 'btn btn-primary btn-lg ' do %>
            All courses <br>
            <div class="fa fa-book fa-5x"></div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="card-group text-center rounded my-5">
  <div class="card">
    <div class="card-body">
      <h3>
        <div class="fa fa-book"></div>
        <%= Course.count %>
        Online courses
      </h3>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h3>
        <div class="fa fa-chalkboard-teacher"></div>
        <%= User.count %>
        Teachers
      </h3>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h3>
        <div class="fa fa-user"></div>
        <%= User.count %>
        Active users
      </h3>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h3>
        <div class="fa fa-infinity"></div>
        Life-time access
      </h3>
    </div>
  </div>
</div>


<hr>

<% if current_user && current_user.enrollments.any? %>
  <h2><div class="fa fa-graduation-cap"></div> Continue learing</h2>
  <div class="card-columns">
    <% @purchased_courses.each do |course| %>
      <%= render course %>
    <% end %>
  </div>
  <div class="text-right">
    <%= link_to "All your purchased courses", purchased_courses_path, class: "" %>
  </div>
<hr>
  
<% end %>

<h2><div class="fa fa-chart-line"></div> Popular courses</h2>
  <div class="card-columns">
    <% @popular_courses.each do |course| %>
      <%= render course %>
    <% end %>
  </div>
  <div class="text-right">
    <%= link_to "More popular courses", courses_path(courses_search: {s: 'enrollments_count desc'} ), class: "" %>
  </div>
<hr>
<h2><div class="fa fa-star"></div> Top rated</h2>
  <div class="card-columns">
    <% @top_rated_courses.each do |course| %>
      <%= render course %>
    <% end %>
  </div>
  <div class="text-right">
    <%= link_to "Top rated courses", courses_path(courses_search: {s: 'average_rating desc'} ), class: "" %>
  </div>
<hr>
<h2><div class="fa fa-clock"></div> Latest courses</h2>
  <div class="card-columns">
    <% @latest_courses.each do |course| %>
      <%= render course %>
    <% end %>
  </div>
  <div class="text-right">
    <%= link_to "More new courses", courses_path(courses_search: {s: 'created_at desc'} ), class: "" %>
  </div>
<hr>
<h2><div class="fa fa-comment"></div> What our students want to say</h2>
  <div class="card-columns">
    <% @enrollments.each do |enrollment| %>
      <%= render 'enrollments/enrollment', enrollment: enrollment %>
    <% end %>
  </div>

app/views/home/privacy_policy.html.erb
<div class="card">
  <div class="card-header">Privacy Policy</div>
  <div class="card-body">
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Debitis necessitatibus labore reiciendis quod nesciunt! Quos libero qui deleniti magnam, pariatur molestiae vitae odio, sequi doloribus veritatis quisquam harum delectus laborum?
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit laborum voluptatibus sed qui facere accusantium, distinctio, illo omnis excepturi eius assumenda, at quidem voluptates sequi! Cumque odio autem voluptatum quisquam.
  </div>
  <div class="card-footer">
    <%= link_to "Back to home", :root, class: "btn btn-primary" %>
  </div>
</div>