config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  devise_for :users, controllers: {  registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lessons
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
  end

  resources :users, only: [:index, :edit, :update, :show]
  root 'home#index'
  get 'activity', to: 'home#activity'
  get 'privacy_policy', to: 'home#privacy_policy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true
  #User.find_each { |user| User.reset_counters(user.id, :enrollments)}

  validates :user, :course, presence: true
  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id #cant be subscribed twice
  validates_uniqueness_of :course_id, scope: :user_id

  validate :owner_cant_subscribe


  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    user.to_s + " " + course.to_s
  end
  
  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }

  after_save do 
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end



  protected

  def owner_cant_subscribe
    if self.new_record?
      if self.user_id.present?
        if self.user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end

  
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy, :certificate]
  before_action :set_course, only: [:new, :create]
  skip_before_action :authenticate_user!, only: [:certificate]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollment_ransack_path = enrollments_path
    @ransack_enrollments = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@ransack_enrollments.result.includes(:user))
    
  end
  
  def my_students
    @enrollment_ransack_path = my_students_enrollments_path
    @ransack_enrollments = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@ransack_enrollments.result.includes(:user))
    render 'index'
  end
  
  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end
  
  def certificate
    authorize @enrollment, :certificate?
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@enrollment.course.title}, #{@enrollment.user.email}",
        page_size: 'A4',
        template: 'enrollments/certificate.pdf.erb'

      end
    end
  end
  
  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end
  
  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end
  
  # POST /enrollments
  # POST /enrollments.json
  def create
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You bought course!"
      EnrollmentMailer.student_enrollment(@enrollment).deliver_later
      EnrollmentMailer.teacher_enrollment(@enrollment).deliver_later
  end
  
  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollment_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_course
      @course = Course.friendly.find(params[:course_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div class="card mb-2">
  <div class="card-header">
    <div class="fa fa-user"></div>
    <%= link_to enrollment.user.username, enrollment.user %>

    <div class="fa fa-clock"></div>
    <%= time_ago_in_words(enrollment.updated_at) %>
    
    <div class="fa fa-graduation-cap"></div>
    <%= link_to enrollment.course.title, enrollment.course %>
  </div>
  <div class="card-body">
    <div class="fa fa-star text-warning"></div>
    <%= enrollment.rating %>

    <div class="fa fa-comment"></div>
    <%= enrollment.review %>
    <div class="fa fa-comment"></div>
    
  </div>
  <% if current_user && policy(enrollment).edit? %>
    <div class="card-footer">
        <%= link_to "Edit review", edit_enrollment_path(enrollment), class: "btn btn-primary" %>
        <%= link_to "Back to course", course_path(enrollment.course), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
    <%= f.input :review %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add review" %>
  </div>
<% end %>

app/views/enrollments/certificate.pdf.erb
<div style="width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #163d7c">
  <div id="header" class="center">
    <h1>Certificate of Completion</h1>
  </div>

  <h2>Course <%= @enrollment.course.title %> for <%= @enrollment.user.email %></h2>

  <h3>User <%= @enrollment.user.email %> succesfully completed course!</h3>
  <h3><b>Certificate id:</b> <%= @enrollment.slug %></h3>
  <h3><b>Certificate url:</b> <%= request.base_url %><%= request.original_fullpath %></h3>
</div>

app/views/enrollments/edit.html.erb
<div class="card">
  <div class="card-header">
    <h1><div class="fa fa-star text-warning"></div> Add review</h1>
  </div>
  <div class="card-body">
    <%= render 'form', enrollment: @enrollment %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show review', @enrollment, class: "btn btn-primary" %> 
    <%= link_to 'Back to course', course_path(@enrollment.course), class: "btn btn-primary" %>
  </div>
</div>

app/views/enrollments/index.html.erb
<h3 class="text-center">
  <%= action_name.humanize %>  enrollments
  <div class="badge badge-primary"><%= @enrollments.count %></div>
</h3>

    <div class="card p-2">
      <%= search_form_for @ransack_enrollments, url: @enrollment_ransack_path do |f| %>
        <%= f.label :rating %>
        <%= f.search_field :rating_eq, placeholder: "Rating", class: "form-control" %>
        <%= f.search_field :user_email_cont, placeholder: "User email", class: "form-control" %>

        <%= f.submit "Search", class: "btn btn-primary my-2" %>
        <%= link_to  @enrollment_ransack_path, class: "btn btn-primary" do %>
            <div class="fa fa-sync"></div>
        <% end %>
      <% end %>

    </div>

<div class="table-responsive">
  <table class = "table table-bordered table-sm table-striped">
    <thead>
      <tr>
        <th><div class="fa fa-graduation-cap"></div> Course name</th>
        <th><%= sort_link(@ransack_enrollments, :user_email, "User") %></th>
        <th><div class="fa fa-clock"></div> Reviewed at </th>
        <th><%= sort_link(@ransack_enrollments, :rating) %></th>
        <th>Review</th>
        <th><%= sort_link(@ransack_enrollments, :progress) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @enrollments.each do |enrollment| %>
        <tr>
          <td><%= link_to enrollment.course.title, enrollment.course %></td>
          <td><%= link_to enrollment.user.email, enrollment.user %></td>
          <td><%= enrollment.created_at.strftime("%d/%b/%Y - %H:%M") %></td>
          <td><%= enrollment.rating %></td>
          <td><%= enrollment.review %></td>
          <td><%= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0) %></td>
          <td><%= link_to 'Show Review', enrollment %></td>
          <% if policy(enrollment).edit? %>
            <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
            <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
      <%== pagy_bootstrap_nav(@pagy) %>

</div>

app/views/enrollments/new.html.erb
<div class="card">
  <div class="card-header">
    <h1>
      <div class="fa fa-graduation-cap"></div>
      Buy course 
      <%= link_to @course.title, course_path(@course) %>
    </h1>
  </div>
  <div class="card-body">
    <%= form_tag course_enrollments_path(@course) do %>
      <% if @course.price > 0 %>
        <%= submit_tag "Pay #{number_to_currency(@course.price)}", class: "btn btn-lg btn-primary" %>
      <% else %>
        <%= submit_tag "Roll in for free!", class: "btn btn-lg btn-primary" %>
      <% end %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', course_path(@course), class: "btn btn-success" %>
  </div>
</div>

app/views/enrollments/show.html.erb
<%= render 'enrollments/enrollment', enrollment: @enrollment %>