config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  devise_for :users, controllers: {  registrations: "users/registrations", omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :lessons
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
  end

  resources :users, only: [:index, :edit, :update, :show]
  root 'home#index'
  get 'activity', to: 'home#activity'
  get 'privacy_policy', to: 'home#privacy_policy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="py-3 bg-light mt-5 border border-top">
  <div class="container">
    <div class="row">
      <div class="col-md-4 border-left">
        <div class="btn btn-light disabled">
          Copyright &copy; <%= Time.now.year %>
        </div>
        <br>
        <div class="btn btn-light">
          <%= mail_to 'arturd444@gmail.com' %>        
        </div>
      </div>
      <div class="col-md-4">
        
      </div>
      <div class="col-md-4 border-left">
        <%= link_to "Privacy Policy", privacy_policy_path, class: "btn btn-light" %>
        
        <br>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-light" data-toggle="modal" data-target="#exampleModal2">
        Abous us       
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModal2Label" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModal2Label">About us</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Lametorem ipsum, dolor sit  consectetur adipisicing elit. Rerum tenetur incidunt suscipit aspernatur. Veritatis fugit ad, impedit aperiam sint repellat officia minima eum in facilis inventore enim odit possimus incidunt!
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.dig(:google_analytics) %>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= Rails.application.credentials.dig(:google_analytics) %>');
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary border-gradient">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div class="fab fa-contao"></div>
      CourseApp
    <% end %>  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse bg-primary rounded" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to courses_path, class: "nav-link" do %>
            <div class="fa fa-book"></div>
            Courses
          <% end %>
        </li>

        <% if current_user %>
          <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path, class: "form-inline" do |f| %>
            <div class="input-group">
              <%= f.search_field :title_or_short_description_cont, placeholder: "Find a course", class: "form-control form-control-sm" %>   
              <div class="input-group-append">
              <button class="btn btn-dark btn-sm" type="submit">
                  <span class="fa fa-search form-control-feedback"></span>
              </button>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>


      <ul class="navbar-nav ml-auto">


        <% if current_user && current_user.has_role?(:admin) %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="adminNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="fa fa-cogs"></div>
              Admin
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="adminNavbarDropdown">
              <%= link_to enrollments_path, class: "dropdown-item" do %>
                <div class="fa fa-lock-open"></div>
                Enrollments
              <% end %>
              <%= link_to activity_path, class: "dropdown-item" do %>
                <div class="fa fa-bell"></div>
                Activity
              <% end %>
              <%= link_to users_path, class: "dropdown-item" do %>
                <div class="fa fa-user"></div>
                Users
              <% end %>
              <%= link_to unapproved_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-graduation-cap"></div>
                Unapproved courses
              <% end %>
            </div>
          </li>
        <% end %>

        <% if current_user && current_user.has_role?(:teacher) %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle " href="#" id="teacherNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="fa fa-chalkboard-teacher"></div>
              Teach
            </a>
            <div class="dropdown-menu dropdown-menu-right " aria-labelledby="teacherNavbarDropdown">
              <%= link_to new_course_path, class: "dropdown-item" do %>
                <div class="fa fa-plus"></div>
                New Course
              <% end %>

              <%= link_to my_students_enrollments_path, class: "dropdown-item" do %>
                <div class="fa fa-user"></div>
                Your students
                <div class="badge badge-danger"><%= Enrollment.joins(:course).where(courses: {user: current_user}).count %></div>
              <% end %>

              <%= link_to created_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-chalkboard-teacher"></div>
                Created courses
                <div class="badge badge-danger"><%= current_user.courses_count %></div>
              <% end %>
            </div>
          </li>
        <% end %>

        <% if current_user && current_user.has_role?(:student) %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="studentNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="fa fa-graduation-cap"></div>
              Learn
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="studentNavbarDropdown">
              <%= link_to purchased_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-graduation-cap"></div>
                Your courses
                <div class="badge badge-danger"><%= current_user.enrollments_count %></div>
              <% end %>
              
              <%= link_to pending_review_courses_path, class: "dropdown-item" do %>
                <div class="fa fa-star"></div>
                Pending review
                <div class="badge badge-danger"><%= current_user.enrollments.pending_review.count %></div>
              <% end %>
            </div>
          </li>
        <% end %>


        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="fa fa-user"></div>
            <%= user_signed_in? ? "#{current_user.email.split("@")[0]}" : "Guest" %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Login", new_user_session_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>





      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "CourseApp" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="online education, course platform, video tutorials, learn" name="keywords"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= flash_messages %>
    <div class="container pt-3">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  </head>
  <body onload='number_pages'>

    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>